repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
    - id: check-yaml
  - repo: local
    hooks:
    - id: pycln
      name: pycln
      entry: poetry run pycln frame tests
      language: system
      types:
        - python
    - id: pylint
      name: pylint
      entry: poetry run pylint frame tests
      language: system
      types:
        - python
    - id: black
      name: black
      entry: poetry run black frame tests
      language: system
      types:
        - python
    - id: isort
      name: isort
      entry: poetry run isort frame tests
      language: system
      types:
        - python
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types:
        - python
      exclude: tests/*
    - id: bandit
      name: bandit
      entry: poetry run bandit -r api/ -ll -c bandit.yaml
      language: system
      stages: [push]
