version: '3.7'
services:
  frame_postgres:
    image: postgres:11.9
    environment:
      - POSTGRES_USER=frame
      - POSTGRES_PASSWORD=frame
      - POSTGRES_DB=frame
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 54321:5432
    volumes:
      - /var/lib/postgresql/data/pgdata
    logging:
        options:
            max-size: 10m
            max-file: "3"

  frame_api:
    depends_on:
      - frame_postgres
    build:
      context: ../
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://frame:frame@frame_postgres/frame"
    entrypoint: /app/docker/api-entrypoint.sh
