"""add station status

Revision ID: 99d2ac2434ae
Revises: 5709ab7a20d4
Create Date: 2022-10-08 18:52:31.512296

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '99d2ac2434ae'
down_revision = '5709ab7a20d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations_status',
        sa.Column('station_id', sa.Integer(), nullable=False),
        sa.Column('num_bikes_available', sa.Integer(), nullable=False),
        sa.Column('num_bikes_disabled', sa.Integer(), nullable=False),
        sa.Column('num_docks_available', sa.Integer(), nullable=False),
        sa.Column('num_docks_disabled', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('last_reported', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('station_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations_status')
    # ### end Alembic commands ###
