"""make last reported nullable

Revision ID: 7f85dff1890c
Revises: 99d2ac2434ae
Create Date: 2022-10-08 20:45:04.894398

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7f85dff1890c'
down_revision = '99d2ac2434ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stations_status") as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(),
            nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stations_status") as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(),
            nullable=False
        )
    # ### end Alembic commands ###
