"""add stations

Revision ID: 5709ab7a20d4
Revises:
Create Date: 2022-09-25 23:15:19.678875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5709ab7a20d4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # pylint: disable=E1101
        "stations",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lat", sa.Numeric(), nullable=True),
        sa.Column("lon", sa.Numeric(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("station_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stations")  # pylint: disable=E1101
    # ### end Alembic commands ###
