"""persist model versions to db

Revision ID: 79b65ae3e0cf
Revises: f6ab8a88245a
Create Date: 2023-02-28 20:00:25.234646

"""
# pylint: disable=E1101

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79b65ae3e0cf"
down_revision = "f6ab8a88245a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "predictions",
        sa.Column("availability_model_version", sa.Integer(), nullable=True),
    )
    op.add_column(
        "predictions", sa.Column("eta_model_version", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("predictions", "eta_model_version")
    op.drop_column("predictions", "availability_model_version")
    # ### end Alembic commands ###
